version: "3.7"
services:
  actions-slack-notification-dev:
    build: .devcontainer
    container_name: actions-slack-notification-dev
    tty: true
    volumes:
      - .:/src
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
