name: test

on:
  push:
    branches: ["main"]

env:
  SLACK_KEY: ${{ secrets.SLACK_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Slack Notification on Success
        uses: ./
        with:
          channel: test
