name: test

on:
  push:
    branches: ["main"]

env:
  SLACK_KEY: ${{ secrets.SLACK_KEY }}
  NOTIFICATION_DEBUG: "y"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Slack Notification on Success
        uses: ./
        with:
          channel: C024CRE9BHP

      - name: Slack Notification on Success
        uses: ./
        with:
          channel: C024CRE9BHP
          color: red
          title: test
          message: test
          mention: "@UK0RTGRPH"
          fields: '[{"title": "test", "value": "test value"}]'
