name: test

on:
  push:
    branches: ["main"]

env:
  SLACK_KEY: ${{ secrets.SLACK_KEY }}
  CANNEL: ${{ secrets.SLACK_CHANNEL }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Slack Notification on Success
        uses: ./
        with:
          channel: ${CANNEL}

      - name: Slack Notification on Success
        uses: ./
        with:
          channel: ${CANNEL}
          color: red
          title: test
          message: test
          mention: "<@UK0RTGRPH>"
          fields: '[{"title": "test", "value": "test value"}]'
